name: Build and test vsts-npm-auth-improved

on:
  push:
    branches:
      - main
    paths:
      - projects/vsts-npm-auth-improved/**
  pull_request:
    paths:
      - projects/vsts-npm-auth-improved/**
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test vsts-npm-auth-improved
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: pwsh
        working-directory: projects/vsts-npm-auth-improved
    env:
      NODE_VERSION: 24.18.1
      NPM_VERSION: 12.0.2
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Build and test package
        uses: ./.github/actions/build-and-test-package
        with:
          project-directory: projects/vsts-npm-auth-improved
          node-version: ${{ env.NODE_VERSION }}
          npm-version: ${{ env.NPM_VERSION }}
